### ISSUE TITLE
PDDL parsing

### ISSUE THREAD

**Issue by mikand** [aiplan4eu/upf#14]
### User Story
As a **planning expert** I want to import existing PDDL benchmarks and models to augment them via code and/or use integrated planning techniques.

The parser should be able to read just a domain or a domain+problem and generate a `Problem` instance.

### Acceptance Criteria

- [ ] IPC classical and numerical planning examples can be successfully parsed
- [ ] A suite of erroneous model is created and added to CI
- [ ] Proper errors are reported to the user

### Additional Material

- We could exploit `tarski` that does offer a PDDL parser
- https://github.com/pucrs-automated-planning/pddl-parser
- https://github.com/pyparsing/pyparsing/
- https://github.com/swayf/grako#id3

### Attention Points

- PDDL has several dialects/fragments depending on the requirements (https://planning.wiki/ref/pddl21/domain) a reasonable subset needs to be identified

**Comment by haz** [comment]
Really can't imagine there being a better solution than adopting `tarski`. Actively developed...covers what you're after...requires little dev-resources since others are doing the development of it...etc.

Also [some hope](https://github.com/aig-upf/tarski/discussions/108) of seeing a new parsing lib used to extend the language being parsed, programmatically.
